IF
  Global("NTYnessSpawn","%UlgothsBeard%",0)
THEN
  RESPONSE #100
    CreateCreature("NTYness",[2587.746],14)
    SetGlobal("NTYnessSpawn","%UlgothsBeard%",1)
    Continue()
END

IF
  Global("NTTalkedToReedig","GLOBAL",1)
  !Exists("NTREEDRI")
  !Dead("NTREEDRI")
//  Dead("TANAR")
  Dead("Tracea")
THEN
  RESPONSE #100
    CreateCreature("NTREEDRI",[1267.769],0)
    SetGlobal("NTTalkedToReedig","GLOBAL",2)
    ActionOverride("NTREEDRI",CreateItem("NTPBLET6",1,0,0))
    Continue()
END



