IF
  Clicked([ANYONE])
  Global("NT_AR01PBFALSEDOORFireball","MYAREA",0)
THEN
  RESPONSE #100
    SetGlobal("NT_AR01PBFALSEDOORFireball","MYAREA",1)
    DisplayStringHead(Myself,14381) //Trap Sprung
    ForceSpell(Player1,TRAP_FIREBALL)
    ForceSpell(Player2,TRAP_FIREBALL)
    ForceSpell(Player3,TRAP_FIREBALL)
    ForceSpell(Player4,TRAP_FIREBALL)
    ForceSpell(Player5,TRAP_FIREBALL)
    ForceSpell(Player6,TRAP_FIREBALL)
END

