WITH_TRA ~ntotsc/language/english/tactical.tra~ ~ntotsc/language/%s/tactical.tra~
BEGIN
  COPY "%MOD_FOLDER%/tactical/actors/ntindfi1.cre" "override"
       "%MOD_FOLDER%/tactical/actors/ntindfi2.cre" "override"
    SAY NAME1 @0
    SAY NAME2 @0

  COPY "%MOD_FOLDER%/tactical/actors/ntindfig.cre" "override"
    SAY NAME1 @1
    SAY NAME2 @1

  ACTION_FOR_EACH script in "ntfiends" "ntmaurez" "ntsuccub"
  BEGIN
    COMPILE EVALUATE_BUFFER "%script%.baf"
  END
END


